#pragma once

#include "NativeGameplayTags.h"

namespace GASCoreTags
{
	// --- Events ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Knockback);

	// --- Movement States ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Crouched);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Airborne);

	// --- Inputs ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SwapAmmo_SetIndex);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SwapAmmo_Cycle);
	
	// --- AI "Inputs" ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AI_Primary);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AI_ReleasePrimary);
	
	// --- States ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_Priming);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Element_Burning);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_LightSource_Lit);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AI_Combat);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AI_Routine);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AI_RespondingToTeam);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AI_Suspicious);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AI_Searching);

	// --- Data ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Magnitude_Force);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Magnitude_Detection);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Attribute_MaxHealth);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Attribute_MaxEnergy);
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Attribute_MaxDetection);

	// --- Effects ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Knockback);

	// --- GameplayCues ---
	GASCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death_Ragdoll);
}