;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Weapon.Fire",DevComment="AnimNotify broadcast tag")
+GameplayTagList=(Tag="Input.Interact",DevComment="Interaction input")
+GameplayTagList=(Tag="Input.Movement.Crouch",DevComment="Crouch input tag")
+GameplayTagList=(Tag="Input.Movement.Jump",DevComment="Jump input")
+GameplayTagList=(Tag="Input.Primary",DevComment="Primary action input (eg. left click)")
+GameplayTagList=(Tag="Input.Secondary",DevComment="Secondary action input (eg. right click)")
+GameplayTagList=(Tag="State.Camera.Zoomed",DevComment="Eg. zooming on a bow")
+GameplayTagList=(Tag="State.Weapon.Priming",DevComment="Used when \"charging\" an attack")

